# Generated by Django 3.0.3 on 2020-04-12 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('ci', models.IntegerField(null=True, unique=True)),
                ('telefono', models.IntegerField(null=True)),
                ('mail', models.EmailField(max_length=254, null=True)),
                ('cuenta_bancaria', models.IntegerField(null=True)),
                ('banco', models.CharField(max_length=50)),
                ('estado', models.BooleanField(default=True)),
                ('username', models.CharField(default='user', max_length=20)),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cuidacoches',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('ci', models.IntegerField()),
                ('num_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(default=None, null=True)),
                ('horario_inicio', models.TimeField(default=None, null=True)),
                ('horario_fin', models.TimeField(default=None, null=True)),
                ('telefono', models.IntegerField(null=True)),
                ('mail', models.EmailField(default=None, max_length=254, null=True)),
                ('fecha_nacimiento', models.DateField(null=True)),
                ('cuenta_bancaria', models.IntegerField(null=True)),
                ('banco', models.CharField(max_length=50, null=True)),
                ('promedio_calificacion', models.FloatField(null=True)),
                ('cantidad_votos', models.IntegerField(null=True)),
                ('estado', models.BooleanField(default=True)),
                ('cant_lugares', models.IntegerField(default=20)),
                ('lugares_disponibles', models.IntegerField(default=models.IntegerField(default=20))),
                ('password', models.CharField(max_length=8, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('nombre', models.CharField(max_length=20)),
                ('apellido', models.CharField(max_length=20)),
                ('ci', models.IntegerField()),
                ('num_registro', models.IntegerField(primary_key=True, serialize=False)),
                ('direccion', models.TextField(default=None, null=True)),
                ('horario_inicio', models.TimeField(default=None, null=True)),
                ('horario_fin', models.TimeField(default=None, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.IntegerField(null=True)),
                ('comentario', models.TextField(max_length=200, null=True)),
                ('fecha', models.DateTimeField(auto_now=True)),
                ('conductor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Conductor')),
                ('cuidacoches', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cuidacoches')),
            ],
        ),
        migrations.CreateModel(
            name='MonederoCuidacoches',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField()),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Cuidacoches')),
            ],
        ),
        migrations.CreateModel(
            name='MonederoConductor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.IntegerField(default=500)),
                ('ci', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.Conductor')),
            ],
        ),
    ]
