# Generated by Django 3.0.5 on 2020-04-12 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='propina',
            field=models.IntegerField(null=True),
        ),
    ]
