# Generated by Django 3.0.3 on 2020-04-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_relacion_propina'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='registro',
            name='nombre_trabajo',
            field=models.CharField(default='Cuidacoches', max_length=20),
        ),
    ]
