# Generated by Django 3.0.3 on 2020-04-13 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200412_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuidacoches',
            name='latitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cuidacoches',
            name='longitud',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='cuidacoches',
            name='nombre_trabajo',
            field=models.CharField(default='Cuidacoches', max_length=20),
        ),
    ]
