# Generated by Django 3.0.3 on 2020-04-13 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20200413_0038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuidacoches',
            name='nombre_trabajo',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='nombre_trabajo',
            field=models.CharField(max_length=50),
        ),
    ]
