# Generated by Django 3.0.5 on 2020-04-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20200413_0053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relacion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
