# Generated by Django 3.0.3 on 2020-04-18 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_conductor_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conductor',
            name='username',
            field=models.CharField(default='user', max_length=20, null=True),
        ),
    ]
